  eureka:
    instance:
      prefer-ip-address: true

    client:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://http://localhost:8761/eureka}
